import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { Posts } from 'src/components/blog'
import { Pagination, usePagination } from 'src/components/pagination'
import { Spinner } from 'src/components/spinner'
import { getBlogposts } from 'src/mock'

const Home: NextPage = () => {
  const {
    display,
    items,
    isLoading,
    currentPage,
    setCurrentPage,
    totalPages,
    loadItems
  } = usePagination()

  useEffect(() => {
    loadItems(getBlogposts()).catch(console.error)
  }, [])

  return (
    <div className="flex flex-col gap-3">
      <Head>
        <title>Header</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {isLoading ? <Spinner /> : <Posts posts={items} />}
        {!isLoading && (
          <Pagination
            currentPage={currentPage}
            setCurrentPage={setCurrentPage}
            totalPages={totalPages}
            display={display}
          />
        )}
      </main>

      <footer className="flex flex-row text-start">
        <span>Footer info</span>
      </footer>
    </div>
  )
}

export default Home
