/* eslint-disable @typescript-eslint/promise-function-async */
/* eslint-disable @typescript-eslint/no-misused-promises */
import Head from 'next/head'
import { Button } from 'src/components/button'

const PopulateUsers = () => {
  const populateUsers = async () => {
    const response = await fetch('/api/populate-users', {
      method: 'POST',
      body: '',
      headers: {
        'Content-Type': 'application/json'
      }
    })

    const data = await response.json()
    console.log(data)
  }

  return (
    <div className="flex flex-col gap-3">
      <Head>
        <title>Populate Users</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className="flex min-h-screen flex-col items-center justify-center">
          <Button type="button" isRounded onClick={() => populateUsers()}>
            Populate Users
          </Button>
        </div>
      </main>

      <footer className="flex flex-row text-start">
        <a href="/blogposts">
          <span>Footer info</span>
        </a>
      </footer>
    </div>
  )
}

export default PopulateUsers
